### ISSUE TITLE
Add an option to create endpoint slice for an imported service

### ISSUE THREAD

**Issue by praveingk** [clusterlink-net/clusterlink#324]
Consider a scenario where a replica of a job are deployed across clusters. However, the load balancing is done from the primary cluster. We would want the remote replica (which is imported as a service in the primary cluster) to be attached as an endpoint slice for the service (hosted as load balancer) in the primary cluster

**Comment by praveingk** [comment]
We would be creating a bool flag -m or --merge while importing service. 
1) If Merge is set to true, we would create an endpointslice with service label set to import service name (which is to be merged with), and cl-dataplane's listener target. We would not be creating an additional service.
2) If Merge is set to false, we would create a new service.

**Comment by elevran** [comment]
while not strictly part of unprivileged mode milestone, it is assigned that as the primary use case. The issue can be handled earlier if needed

**Comment by praveingk** [comment]
@elevran I tried to create endpointslice using FQDN, but I do not see that it gets routed correctly. Additionally, Also observed a warning message of `Warning: spec.addressType: FQDN endpoints are deprecated` when I create an endpointslice with endpoint address as FQDN. 
If we rule out using FQDN, then the only option is to use IPv4 address of the `cl-dataplane` pod. However, we would need to handle the case when `cl-dataplane` pod IP changes. Hence, we might need to check pod updates to cl-dataplane and if it undergoes any change, we would need to change all endpointslice address.
Please let me know your suggestion.

**Comment by elevran** [comment]
@praveingk the FQDN addresses in EndpointSlice are apparently a dead end due to them being [ignored by kubeproxy]https://github.com/kubernetes/kubernetes/issues/105172#issuecomment-928259562) and [results in deprecated message](https://github.com/kubernetes/kubernetes/issues/114210).

It seems that the control plane controller would indeed need to add IPv4/6 EndpointSlice (start with IPv4) and keep it up to date with changes in the cl-dataplane pods IP addresses.
I don't see a different option for now
